<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>ServiceAppointment.Cancellation_of_SA</members>
		<name>ApprovalProcess</name>
	</types>
	<types>
		<members>ServiceAppointment.Productive_Unproductive__c</members>
		<members>ServiceAppointment.Upv_Reason__c</members>
		<name>CustomField</name>
	</types>
	<types>
		<members>Assigned_Resource_Update_to_SA</members>
		<members>SA_Assignment_to_ASP</members>
		<members>Work_Order_Creation_Interio</members>
		<members>Work_Order_Generation_Screen_Flow</members>
		<name>Flow</name>
	</types>
	<types>
		<members>aSPInventory</members>
		<members>bomRequest</members>
		<name>LightningComponentBundle</name>
	</types>
	<types>
		<members>Account.Create_an_Asset</members>
		<members>Case.Work_Order_Generation</members>
		<name>QuickAction</name>
	</types>
	<types>
		<members>GVLC</members>
		<name>RemoteSiteSetting</name>
	</types>
	<types>
		<members>ServiceAppointment.Populate_the_reason_for_reschedule</members>
		<members>ServiceAppointment.Unproductive_Reason_is_mandatory</members>
		<name>ValidationRule</name>
	</types>
	<version>60.0</version>
</Package>
