<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>ASPInventoryController</members>
		<members>ASPInventoryControllerTest</members>
		<members>AssetScreenFlowComponentController</members>
		<members>AssetScreenFlowComponentControllerTest</members>
		<members>BOMRequestController</members>
		<members>BOMRequestControllerTest</members>
		<members>JobCodeMasterController</members>
		<members>JobCodeMasterControllerTest</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>Asset.Actual_Product_Category__c</members>
		<members>Asset.Actual_Product_Subcategory__c</members>
		<members>JobCodeMaster__c.Product_Category__c</members>
		<members>JobCodeMaster__c.Product_Subcategory__c</members>
		<members>Order.Actual_Problem__c</members>
		<members>ServiceAppointment.Business_Unit__c</members>
		<members>ServiceAppointment.Productive_Unproductive__c</members>
		<members>ServiceAppointment.Upv_Reason__c</members>
		<name>CustomField</name>
	</types>
	<types>
		<members>Upv_Reason.Address_Not_Found_H</members>
		<members>Upv_Reason.Address_Not_Found_L</members>
		<members>Upv_Reason.Address_Not_Found_U</members>
		<members>Upv_Reason.Address_Not_Found_W</members>
		<members>Upv_Reason.Already_Attended_H</members>
		<members>Upv_Reason.Already_Attended_L</members>
		<members>Upv_Reason.Already_Attended_U</members>
		<members>Upv_Reason.Call_Center_to_Call_Back_H</members>
		<members>Upv_Reason.Carpentry_Work_Required_L</members>
		<members>Upv_Reason.Concern_Person_Not_Available_L</members>
		<members>Upv_Reason.Customer_Not_Responding_L</members>
		<members>Upv_Reason.Customer_Said_No_Complaint_H</members>
		<members>Upv_Reason.Customer_Said_No_Complaint_L</members>
		<members>Upv_Reason.Customer_Said_No_Complaint_U</members>
		<members>Upv_Reason.Customer_Said_No_Complaint_W</members>
		<members>Upv_Reason.Customer_giving_revised_date_W</members>
		<members>Upv_Reason.Customer_to_revert_UPV_call</members>
		<members>Upv_Reason.Customer_will_Contact_H</members>
		<members>Upv_Reason.Customer_will_Contact_U</members>
		<members>Upv_Reason.Depreciation_Pending_H</members>
		<members>Upv_Reason.Did_Not_Allow_H</members>
		<members>Upv_Reason.Did_Not_Allow_To_Check_L</members>
		<members>Upv_Reason.Did_Not_Allow_U</members>
		<members>Upv_Reason.Did_Not_Allow_W</members>
		<members>Upv_Reason.Duplicate_Call_H</members>
		<members>Upv_Reason.Duplicate_Call_L</members>
		<members>Upv_Reason.Duplicate_Call_U</members>
		<members>Upv_Reason.Estimate_Given_Party_will_Inform_W</members>
		<members>Upv_Reason.House_Locked</members>
		<members>Upv_Reason.House_Locked_U</members>
		<members>Upv_Reason.House_Locked_W</members>
		<members>Upv_Reason.Indemnity_Bond_not_prepared_L</members>
		<members>Upv_Reason.Indemnity_Bond_not_prepared_U</members>
		<members>Upv_Reason.Later_Date_Appointment_L</members>
		<members>Upv_Reason.Machine_Not_Delivered_H</members>
		<members>Upv_Reason.Main_Customer_NA_H</members>
		<members>Upv_Reason.Main_Customer_Not_Available_U</members>
		<members>Upv_Reason.No_Power_Electricity_L</members>
		<members>Upv_Reason.No_Power_H</members>
		<members>Upv_Reason.No_Power_U</members>
		<members>Upv_Reason.Non_Godrej_Product_L</members>
		<members>Upv_Reason.Non_Wooden_Frame_L</members>
		<members>Upv_Reason.Outside_Policy_Closure_H</members>
		<members>Upv_Reason.Pending_Online_Closure_H</members>
		<members>Upv_Reason.Product_Not_Delivered_U</members>
		<members>Upv_Reason.Site_Not_Ready_On_Hold_L</members>
		<members>Upv_Reason.Site_Not_Ready_for_Work</members>
		<members>Upv_Reason.Site_On_Hold_H</members>
		<members>Upv_Reason.Site_not_ready_over_7_days_W</members>
		<members>Upv_Reason.Tools_Not_Available_U</members>
		<members>Upv_Reason.Unauthorized_Seller_Purchase_U</members>
		<members>Upv_Reason.Warranty_AMC_Paper_NA_H</members>
		<members>Upv_Reason.Warranty_AMC_Paper_Not_Available_U</members>
		<members>Upv_Reason.Warranty_Amc_Document_Not_Available_L</members>
		<name>CustomMetadata</name>
	</types>
	<types>
		<members>Upv_Reason__mdt</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>Account_Customer_Type</members>
		<members>Assigned_Resource_Update_to_SA</members>
		<members>Product_Request_Transfer_Button</members>
		<members>SA_Assignment_to_ASP</members>
		<members>Sales_Order_Generation_button</members>
		<members>Service_Appointment_Completion_FSL_Screen</members>
		<members>Update_SA_status_to_dispatch</members>
		<members>Work_Order_Creation_Interio</members>
		<members>Work_Order_Generation_Screen_Flow</members>
		<name>Flow</name>
	</types>
	<types>
		<members>aSPInventory</members>
		<members>assetScreenFlowComponent</members>
		<members>bomRequest</members>
		<name>LightningComponentBundle</name>
	</types>
	<types>
		<members>Account.Create_an_Asset</members>
		<members>Case.Work_Order_Generation</members>
		<name>QuickAction</name>
	</types>
	<types>
		<members>GVLC</members>
		<name>RemoteSiteSetting</name>
	</types>
	<types>
		<members>ServiceAppointment.Populate_the_reason_for_reschedule</members>
		<members>ServiceAppointment.Unproductive_Reason_is_mandatory</members>
		<name>ValidationRule</name>
	</types>
	<version>60.0</version>
</Package>
